### ISSUE TITLE
png2sprite.py errors

### ISSUE THREAD

**Issue by blackknight36** [commanderx16/x16-demo#18]
This script is erroring out when I try to run it on one of my bitmap files.

```
17:27 $ ../tools/png2sprite.py -n 10000 -f basic KRAKEN.PNG test.txt 
Traceback (most recent call last):
  File "../tools/png2sprite.py", line 84, in <module>
    r, g, b, a = p[y][x]
TypeError: 'numpy.uint8' object is not iterable
```

The bitmap I'm using is from NES ROM data which is 4 bits per pixel.  Any idea how to fix this?  Line 84 appears to be reading pixel color data however I'm not familiar with the PIL module.

**Comment by SleepIT** [comment]
The PNG has to be in RGBA format or you'll get this error!

**Comment by mist64** [comment]
Documentation pull request? :-)

**Comment by blackknight36** [comment]
@SleepIT Would it be possible to detect the color format and print out an error message if the file isn't in RGBA format?  I've done something similar with bitmap files by reading the bpp field.

**Comment by bcbock** [comment]
When I make, I get this error:

$ make
python3 ../tools/png2sprite.py -n balloon balloon.png balloon.inc
Traceback (most recent call last):
  File "../tools/png2sprite.py", line 30, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
make: *** [balloon.inc] Error 1

**Comment by blackknight36** [comment]
@bcbock There's a few python modules you'll need for the script to work.  For example, on RedHat based systems run "yum install python36-pillow  python36-numpy" which will install the PIL and numpy modules.

**Comment by Frank-Buss** [comment]
Fixed:
https://github.com/commanderx16/x16-demo/pull/28

**Comment by daitangio** [comment]
I propose to close this issue.
