### ISSUE TITLE
aritm-x16.bas has a duplicate line number

### ISSUE THREAD

**Issue by EgonOlsen71** [commanderx16/x16-demo#34]
Line number 1420 in the arithm-x16.bas is a duplicate. I'm not sure if simply numbering the second line 1425 is the right fix though.

**Comment by mobluse** [comment]
Good catch! I fixed it now in pull request https://github.com/commanderx16/x16-demo/pull/35.

**Comment by mobluse** [comment]
The pull request is merged now. I think this issue could be closed.
