### ISSUE TITLE
sei and cli in demo-code

### ISSUE THREAD

**Issue by shufps** [commanderx16/x16-demo#4]
probably the comments are wrong for:

    // disable interrupts
    __asm__("sei");

    // enable interrupts
    __asm__("cli");

**Comment by mist64** [comment]
They are correct. The I flag is the inverse from the 80x86. :-)

**Comment by shufps** [comment]
lol ... "SEI (SEt Interrupt-disable bit)" ... 

It's not only on the x86 ... it's also on e.g. 8Bit AVR the same xD

okay, sorry for my reported issue xD
