### ISSUE TITLE
DEMO.PRG crashes emulator

### ISSUE THREAD

**Issue by 3vi1** [commanderx16/x16-demo#51]
I haven't looked into why yet, but DEMO.PRG crashes the emulator.  Other demos work fine - built clean from source today (10/5).

```
15:01:15 evil@P950ER ~/src/x16-demo/release/PRG» x16emu -prg SWIMMER.PRG
15:01:56 evil@P950ER ~/src/x16-demo/release/PRG» x16emu -prg ARITM-X16.PRG 
15:06:36 evil@P950ER ~/src/x16-demo/release/PRG» x16emu -prg BLINKEN.PRG 
15:07:45 evil@P950ER ~/src/x16-demo/release/PRG» x16emu -prg CX16LOGO.PRG 
15:08:28 evil@P950ER ~/src/x16-demo/release/PRG» x16emu -prg DEMO.PRG 
Dumped system to dump.bin.
15:08:38 evil@P950ER ~/src/x16-demo/release/PRG» 
```

**Comment by greg-king5** [comment]
cc65 doesn't work with the latest commits of the Kernal.  It's designed for release 32 of the emulator.  (The ROM banks were changed.)

**Comment by greg-king5** [comment]
cc65 has been updated, [in its repository](/cc65/cc65), for x16-emu release 33.  The sprite demo runs normally for me.

**Comment by 3vi1** [comment]
That's the same repository I built it from.  Again, just now, I pulled git updates for cc65 and all the x16 projects from current source.  Then I did a 'make clean', 'make', and 'sudo make install PREFIX=/usr' on the cc65 project (which cc65 shows I'm using the version I just build).  Then I did a 'make clean', 'make' on the x16-rom project and copied the bins to the x16-emulator source directory.  Then I did a 'make clean' and 'make' on the x16-emulator, and x16-demos projects.

However, it still dumps when I run DEMO.PRG.

I've verified that the cc65 I'm using is the one I just built ('which cc65') and that I'm running the demo with the x16emu that I just compiled.  Puzzling, since there are no compile errors and everything else works fine.

**Comment by 3vi1** [comment]
Wait, you said "**The sprite demo runs normally for me.**".  We're not talking about SPRITE-DEMO.PRG, but DEMO.PRG.  The sprite demo works fine for me too.

**Comment by greg-king5** [comment]
"cc65-sprite/demo.prg" works for me on x16emu R33.  I haven't tested it with the _current_ ROM and emulator code-base.

**Comment by 3vi1** [comment]
I think we may have uncovered two bugs here:

There's no make "clean" option in the root of x16-demo.  And, make wasn't re-making my binary for "demo.prg" for some reason.

I just now went into cc65-sprite and did a make clean there, after I noticed demo.prg was outdated even after a fresh 'make'.

HOWEVER... the second bug is that now the balloons are static... not moving up and down as in previous versions.  Is that happening for you too?  I haven't bothered to look at the code yet.

**Comment by greg-king5** [comment]
> HOWEVER ... the second bug is that, now, (though it doesn't crash) the balloons are static ... not moving up and down, as in previous versions. Is that happening for you too? I haven't bothered to look at the code yet.

I'm surprised that you saw even that much!  The "breaking" change commanderx16/x16-rom@43db14eb248d0527a832939b204fc445b2f7220d should crash all cc65 `cx16` programs.
