### ISSUE TITLE
Contrib guidelines (proposal)

### ISSUE THREAD

**Issue by daitangio** [commanderx16/x16-demo#52]
IMHO I think we should add a small  contribution guidelines in a form of a file called CONTRIBUTING.md.

I can take care of it, if the rest of the team agree.
I think we could add at least:

For basic files:
1. contribute with .bas file (not binary)
2. bas file must be in ascii UTF-8 (not sure if it is right) with uppercase letter 
3. If needed renumber them using the renumber tool
4. if subrotudine, provide at least one usage example
5. Do not forget to add AUTHOR AND LICENSE information in the head of the file via REMs

For assembly code:
1. Group your code in one directory per project
2. Include a Makefile per project
3. Include the directory in the main Makefile, adding it to the SUBDIRS variable (first line) 
4. Test it (see HOW TO COMPILE in the README)
5. Do not forget to add AUTHOR AND LICENSE information in the head of the file via ; comments

Do you have other concepts we need to add to these guidelines?

**Comment by mist64** [comment]
Great, please send a pull request.
