### ISSUE TITLE
Failed to compile: cl65: No such target system: `cx16'

### ISSUE THREAD

**Issue by daitangio** [commanderx16/x16-demo#53]
When I try to compile  the adudio part I get:
>make[1]: Entering directory '/mnt/s/code/x16-demo/cc65-audio'
>cl65 -t cx16 -O -o audio.prg main.c
>cl65: No such target system: `cx16'

My cc65 version:
>$ cc65 --version
>cc65 V2.16 - Ubuntu 2.16-2

Which version of cc65 I need to use to fix it? I need a special configuraiton?

**Comment by Danl2620** [comment]
The machine definition for the x16 hasn't been merged into the main cc65 repo yet. You can clone https://github.com/greg-king5/cc65/tree/commander-x16 and use it as is for now.

**Comment by greg-king5** [comment]
The `cx16` target has gone "mainstream"!  But, cc65's version number now is `2.18`.

You might be able to get a current package for Ubuntu by reading [this wiki page](/cc65/wiki/wiki/OBS%3A-Debian-.DEB-and-RPM).

**Comment by daitangio** [comment]
Thank ypu. I plan to update the README adding the correct, tested rules to install the right toolchain. Then I will propose to close the issue.

**Comment by DealPete** [comment]
I have version `2.18` installed on macOS with homebrew, and I'm still receiving this error.

**Comment by daitangio** [comment]
2.18 has been released on May, 30
cx16 extension seems near  September
https://github.com/cc65/cc65/commit/18afc7c7038280e2443c64e31cf2f0092a484004#diff-b3e4e70de9d1469ed9b1f22ed5c9f3d9

cx16.h  is from September, 27;
https://github.com/cc65/cc65/commits/9fa90e2265b0d54e3fd9e6ec0227821f6a09d9de/include/cx16.h

So I think we should use the master branch or a snapshot binary until a new release of cc65 is blessed.

**Comment by DealPete** [comment]
Hi daitangio. I mistook greg-king5's comment to mean that version 2.18 supported the Commander X16. Thanks for clearing that up.

**Comment by LRFLEW** [comment]
This issue can probably be closed. cc65 [V2.19](https://github.com/cc65/cc65/releases/tag/V2.19) includes the cx16 target, so the issue should be resolved now.

Though that release may be using the old prototype's memory map...

**Comment by edthedev** [comment]
Just FYI for anyone getting here from a Raspberry Pi:
It looks like the available version of `cc65` for Raspbian is still on 2.17, as of 2021 Nov. 

```
$ cc65 -V
cc65 V2.17 - Raspbian 2.17-1
$ sudo apt upgrade cc65
Reading package lists... Done
Building dependency tree       
Reading state information... Done
cc65 is already the newest version (2.17-1).
```

I believe downloading and directly installing this package may resolve this problem for Raspbian users.
https://packages.debian.org/sid/arm64/cc65/download
