### ISSUE TITLE
Some programs doesn't set screen mode right, due to change in SYS $FF5F

### ISSUE THREAD

**Issue by mobluse** [commanderx16/x16-demo#81]
Some programs that contain SYS $FF5F doesn't change screen mode. Right now it is:
https://github.com/commanderx16/x16-demo/blob/master/basic/CX16LOGO.bas
https://github.com/commanderx16/x16-demo/blob/master/basic/aritm-x16.bas

All such programs:
https://github.com/commanderx16/x16-demo/search?q=%24FF5F&unscoped_q=%24FF5F

See:
https://github.com/commanderx16/x16-demo/pull/80
https://github.com/commanderx16/x16-docs/issues/25

**Comment by mist64** [comment]
The last instances were fixed in 4971620
