### ISSUE TITLE
The mouse is overwriting the position of the first sprite in cc65-sprite demo

### ISSUE THREAD

**Issue by haakonnessjoen** [commanderx16/x16-demo#90]
If you write `mouse 0` before `run`, the problem is gone.

I tried adding mouse_hide(), or even mouse_unload() to main(). But that didn't help at all.

**Comment by mist64** [comment]
This should be fixed in r35, can you check?

**Comment by haakonnessjoen** [comment]
In r35, the demo no longer moves any of the sprites.

**Comment by greg-king5** [comment]
> In r35, the demo no longer moves any of the sprites.
> It seems to lock up, since pressing any key does not exit the demo any longer either.

A lot of Kernal variables were moved between r34 and r35!  cc65's library hasn't been updated, yet.

For example, the TIME variable was moved from low memory into banked RAM.  Therefore, the current `waitvsync()` cannot work in r35 (I used TIME as an indirect -- but simple -- measure of VERA's vertical sync interrupts).

**Comment by mist64** [comment]
The cc65 library should no longer export KERNAL variables such as TIME. There are APIs for this particular one, and if there are no APIs for other useful variables, I'm happy to add them.

**Comment by greg-king5** [comment]
We don't want to waste time going through the Kernal.  That's especially true about the vertical sync.  We want our programs to have as many cycles as possible to push data into VERA before it begins to display stuff.

**Comment by mist64** [comment]
The X16 can be easy to program, but it can also be powerful and flexible. In easy to program mode, you leave the IRQ handler as it is, and use KERNAL APIs to make your life easier. In flexible mode, you can replace the IRQ handler, and avoid all KERNAL calls.

I am not sure there is any middle ground here. We can't have a stable yet evolving variable layout.

**Comment by greg-king5** [comment]
> This should be fixed in r35, can you check?

Yes, it's fixed.  You can close this.
