### ISSUE TITLE
Can't compile cc65-sprite

### ISSUE THREAD

**Issue by Apple2007** [commanderx16/x16-demo#97]
I am having an issue with the cc65 part of the makefile. When I type in the command that was listed in the makefile, it shows a lot of errors. Is it me or is the code?

**Comment by greg-king5** [comment]
> I am having an issue with the cc65 part of the makefile. When I type in the command that was listed in the makefile, it shows a lot of errors. Is it me, or is it the code?

Have you updated your cc65 installation to the latest revision?  (Your installation might not know about the Commander X16.)

**Comment by Apple2007** [comment]
Yes. I did before this issue arose.

**Comment by greg-king5** [comment]
>> Have you updated your cc65 installation to the latest revision?
>
> Yes. I did before this issue arose.

In that case, I will need to see some of those error messages, in order to know why the file can be compiled by me, but not by you.

**Comment by Apple2007** [comment]
Here you go:
`demo.c(105): Error: Undefined symbol: 'balloon'
demo.c(105): Error: Subscripted value is neither array nor pointer
demo.c(107): Error: Subscripted value is neither array nor pointer`

**Comment by greg-king5** [comment]
The cl65 command does need the python command to have been done first.  That python command creates a header file that's included into the C file (during compilation).

**Comment by Apple2007** [comment]
That didn't work. I got:
`can't open file 'cl65': [Errno 2] No such file or directory
`
